/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

'use strict';

const vscode = require('vscode');

const CHECKLIST_FILENAME = 'AIDE_CHECKLIST.md';

function defaultChecklistTemplate() {
	const today = new Date().toISOString().slice(0, 10);

	// Keep this file ASCII-only to satisfy VS Code hygiene.
	const lines = [
		'# AIDE Project Checklist',
		'',
		'> Single source of truth for roadmap/todo. Generated by AIDE.',
		'',
		`Started: ${today}`,
		'',
		'<!-- AIDE:BEGIN -->',
		'',
		'## Milestones',
		'',
		'- [ ] M1 - Setup & Tooling',
		'\t- [ ] TASK-001: Install toolchain (Node/Python)',
		'\t- [ ] TASK-002: Fork + build/watch + run dev instance',
		'\t- [ ] TASK-003: Create built-in extension skeleton (aide-checklist)',
		'',
		'- [ ] M2 - Checklist + Brain MVP',
		'\t- [ ] TASK-010: Parser + patcher for checklist',
		'\t- [ ] TASK-011: Hidden brain store (local)',
		'\t- [ ] TASK-012: Check engine (validate -> auto-tick)',
		'',
		'## Current Task',
		'- TASK-003',
		'',
		'## Notes',
		'- Rules: patch-only edits, safe-first, no secrets in prompts.',
		'',
		'<!-- AIDE:END -->',
		''
	];

	return lines.join('\n');
}

async function openFile(uri) {
	const doc = await vscode.workspace.openTextDocument(uri);
	await vscode.window.showTextDocument(doc, { preview: false });
}

async function getWorkspaceRootUri() {
	const folders = vscode.workspace.workspaceFolders;
	if (!folders || folders.length === 0) {
		vscode.window.showErrorMessage('AIDE: Please open a folder/workspace first.');
		return null;
	}
	return folders[0].uri;
}

async function ensureChecklistFile(rootUri) {
	const fileUri = vscode.Uri.joinPath(rootUri, CHECKLIST_FILENAME);

	try {
		await vscode.workspace.fs.stat(fileUri);
		return { fileUri, existed: true };
	} catch {
		// continue
	}

	const data = new TextEncoder().encode(defaultChecklistTemplate());
	await vscode.workspace.fs.writeFile(fileUri, data);
	return { fileUri, existed: false };
}

/**
 * @param {vscode.ExtensionContext} context
 */
function activate(context) {
	const initCmd = vscode.commands.registerCommand('aide.checklist.init', async () => {
		const rootUri = await getWorkspaceRootUri();
		if (!rootUri) {
			return;
		}

		const result = await ensureChecklistFile(rootUri);
		await openFile(result.fileUri);

		vscode.window.showInformationMessage(
			result.existed
				? 'AIDE checklist already exists. Opened AIDE_CHECKLIST.md.'
				: 'Created AIDE_CHECKLIST.md.'
		);
	});

	const openCmd = vscode.commands.registerCommand('aide.checklist.open', async () => {
		const rootUri = await getWorkspaceRootUri();
		if (!rootUri) {
			return;
		}

		const fileUri = vscode.Uri.joinPath(rootUri, CHECKLIST_FILENAME);
		try {
			await vscode.workspace.fs.stat(fileUri);
			await openFile(fileUri);
		} catch {
			vscode.window.showWarningMessage('AIDE_CHECKLIST.md not found. Run: "AIDE: Init Checklist".');
		}
	});

	context.subscriptions.push(initCmd, openCmd);
}

function deactivate() {}

module.exports = { activate, deactivate };
